services:
  api:
    image: echo-api:latest
    container_name: echo-api
    ports:
      - "8080:3000"
    depends_on:
      - mongodb
    networks:
      - api-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local